[package]
name = "beam"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", features = ["serde", "clock"] }
dirs = "6.0"
gpui = { git = "https://github.com/zed-industries/zed" }
gpui-component = { path = "../gpui-component/crates/ui", features = ["tree-sitter-javascript"] }
gpui-component-assets = { path = "../gpui-component/crates/assets" }
gpui_platform = { git = "https://github.com/zed-industries/zed", features = ["font-kit", "x11", "wayland", "runtime_shaders"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
toml = "0.8"
ulid = { version = "1.2", features = ["serde"] }
reqwest = { version = "0.12", default-features = false, features = ["multipart", "rustls-tls"] }
tokio = { version = "1", features = ["rt-multi-thread", "sync", "macros"] }
rust-embed = "8.8"
rquickjs = { version = "0.9", features = ["chrono"] }
log = "0.4"

[dev-dependencies]
tempfile = "3.20"

[package.metadata.bundle]
name = "Beam"
identifier = "com.hlcfan.beam"
version = "0.1.0"
copyright = "Copyright (c) 2025 Beam"
category = "Developer Tool"
short_description = "A HTTP client for developers"
long_description = "Beam is a HTTP client."
icon = ["assets/icon.icns"]
